# Generated by Django 4.1.3 on 2022-12-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_date_alter_articles_text_and_more'),
    ]

    operations = [
    ]
